packages/eslint-config-eventbrite-legacy/README.md
packages/eslint-config-eventbrite-react/.eslintrc.json
packages/eslint-config-eventbrite-react/README.md
packages/eslint-config-eventbrite-react/index.js
packages/eslint-config-eventbrite-react/package.json
packages/eslint-config-eventbrite-react/rules/react-a11y.js
packages/eslint-config-eventbrite/.eslintrc.json
packages/eslint-config-eventbrite/README.md

Also:
- Add blurb about contributing
- Switch to use `eslint-config-eventbrite-legacy` for .eslintrc.json files

Add eslint-plugin-jsx-a11y

---

packages/eslint-config-eventbrite-legacy/package.json
packages/eslint-config-eventbrite-react/package.json
packages/eslint-config-eventbrite/package.json
packages/eslint-config-eventbrite/rules/es6.js

Also bump eslint version to 2.11.1

Add new/missing ES6 ESLint rules

---

packages/eslint-config-eventbrite-react/rules/react.js
react/README.md

Starting off the React documentation with:
- Component structure
- JSX styling
Pretty much all of the rules or eslint-enforced.

Begin React documentation

---

backbone/README.md

Typo in classname

---

react/README.md

Has a bunch miscellaneous guidelines based upon our ESLint rules 😄

Part 3 of React documentation

---

general/README.md

adding docs for IFFE anti-pattern (at least in ES5 and above) as per @gagoar request

adding IFFE docs

---

react/README.md

Also:
- Move state section to the end so that all of the eslint- and syntax-related best practices are all grouped together.
- Create new section to talk about `render()`-related best practices

Add docs for helper components best practice

---

react/README.md

Contains docs on:
- Use of `render()`
- Use of `state`

React docs part 5

---

es6/README.md
react/README.md

Contains docs about:
- `className` prop
- event handlers + state
- scaffolding for ES6 documentation

React docs part 6

---

react/README.md

- Added documentation on best practices for passing children
- Added section on use of mounting

React docs part 7

---

react/README.md
react/testing.md

Adding documentation on React boolean `propTypes`.
Also adding some placeholders for upcoming React documentation.

React docs part 8

---

react/README.md

Add docs on not using context

---

backbone/README.md

Adding and updating our testing docs from main eng docs to this repo. Will add a link where old docs were to new docs location

Jp add testing docs

---

react/testing.md

Initial start at docs for testing React components. Also adds in placeholders for forthcoming docs.

React testing docs part 1

---

react/testing.md

Sections added:
- Testing philosophy
- Writing a test case
- Testing render
- Testing events
- Testing state
- Testing updated props

React testing docs parts 2 & 3

---

es6/README.md

Added overall structure plus details for `Variables`, `String` & `Arrays`

First pass at ES6+ documentation

---

es6/README.md

- rest parameters
- default parameters
- spread operator

ES6 docs Part 4

---

es6/README.md
react/README.md

- Classes
- Modules
- Rest/spread operator spacing

ES6 docs part 5

---

general/README.md

Hi. I was reading through your fantastic JavaScript Coding Style Guide and noticed a few misspelled words. I've provided my suggested changes.
Thanks,
Sean

Fixes misspelled words

---

packages/eslint-config-eventbrite-react/rules/react-a11y.js

Jenn Wong and I would like to add a few of the newer a11y tags! We are happy to discuss if there are any concerns. Thanks!

add some of the new a11y rules

---

react/README.md

Found a couple of mistakes in some of the code examples

Minor fixes/typos to React coding style guide

---

react/README.md

Great style guide! Fixed a small typo.

Fixes minor typo in React coding style guide

---

es6/README.md
general/README.md

We need an Iterators section, so I have added one.

Adding Iterators section.

---

general/README.md
packages/eslint-config-eventbrite/rules/errors.js

Add commas section to general styleguide

---

es6/README.md

Add proposed ways to write bound functions within classes
