packages/eslint-config-eventbrite-legacy/package.json
packages/eslint-config-eventbrite-react/package.json
packages/eslint-config-eventbrite-react/rules/react.js
packages/eslint-config-eventbrite/package.json

Also changing the peerDependencies back to using caret syntax since it's possible that we'll add new rules not available in previous versions of packages

Add missing React & JSX eslint rules

---

packages/eslint-config-eventbrite-legacy/README.md
packages/eslint-config-eventbrite-legacy/rules/best-practices.js
packages/eslint-config-eventbrite-react/README.md
packages/eslint-config-eventbrite-react/rules/react-a11y.js
packages/eslint-config-eventbrite-react/rules/react.js
packages/eslint-config-eventbrite/README.md
packages/eslint-config-eventbrite/index.js
packages/eslint-config-eventbrite/package.json
packages/eslint-config-eventbrite/rules/errors.js
packages/eslint-config-eventbrite/rules/es6.js
packages/eslint-config-eventbrite/rules/esnext.js
packages/eslint-config-eventbrite/rules/style.js

Changes include:
- (temporarily) turning off `no-unused-expressions` until we can figure out a solution to make it work with chai's expectation syntax that looks like unused expressions
- (temporarily) turning off `react/prop-types` until we can implement the update so that it ignores stateless functions that we use for helper components and don't want to define `propTypes` for
- `eslint-config-eventbrite` depends on `babel-eslint` so it can lint ES2016+ and provided a place for ES2016+ rules to go
- `comma-dangle` allows dangling commas for multi-line things
- only function expressions (arrow functions) allowed in ES6+
- ignore imports for `no-useless-rename`
- set `allowParens` to `true` for `no-confusing-arrow` (i.e. arrow functions aren't confusing if you use parentheses)
- validate …

Relaxing some ESLint rules

---

general/README.md

Just a little typo here I think.

Removed extra space from general-multi_if_statement

---

README.md
es5/README.md
es6/README.md
react/README.md

Adding the `propTypes` section of the documentation as well as `displayName`. There are other misc structural changes.

React prop types docs

---

packages/eslint-config-eventbrite-legacy/rules/best-practices.js
packages/eslint-config-eventbrite-legacy/rules/style.js
packages/eslint-config-eventbrite-react/rules/react.js

- `dot-notation` needs to handle uppercase snake_case
- `indent` needs to have normal indentation for `switch` blocks
- `operator-linebreak` should allow either placement
- `jsx-handler-names` should prefix `_handler` w/ underscore

ESLint fixes from linting EB React codebase

---

backbone/README.md

Removed testing docs that are also in /frontend. Added the `reading` section from the testing section to the /frontend repo. Moved `folder_structure` to right before `file_structure`.

remove duplicate test docs, move file structure

---

es6/README.md

Also removed rule for template literals and single quotes

Add ES6 docs on arrow functions

---

packages/eslint-config-eventbrite-legacy/index.js
packages/eslint-config-eventbrite-legacy/rules/best-practices.js

- Our individual repos should add app-specific eslint globals as needed instead of everyone implicitly inheriting them
- `no-unused-expressions` was turned off for chai matcher issues but should be turned off only in the repos with problems not everywhere

Remove eslint globals + reenable no-unused-expressions rule

---

react/README.md

The original document was deleted in https://github.com/facebook/react/commit/455d2d1b48e5cdaeac5d0b4fd92b29b4d52bcaec - changing link to directly reference the last available version.

Fix link to "Props in getInitialState as an anti-pattern"

---

general/README.md

1) Fixed syntax error on `var type` declaration
2) Fixed syntax error on `var translatedGreeting` declaration
3) Fixed typo `IFFE` -> `IIFE` for immediately-invoked function expressions

Fix syntax and spelling error in JS style guide

---

react/testing.md

Awesome guide to testing React components!
There this one minor flaw where prop name `value` is used instead of intended `initialValue`.

Fix prop name in React testing example

---

packages/eslint-config-eventbrite-react/README.md
packages/eslint-config-eventbrite-react/package.json
packages/eslint-config-eventbrite-react/rules/react-a11y.js

It seems that some rules were added that were incompatible with existing version of jsx-a11y package, resulting in `rule not found` errors. The fix is to upgrade `eslint-plugin-jsx-a11y` and replace old rules with new ones! @jenjwong @rwholey-eb

Replace old rules in jsx-a11y

---

packages/eslint-config-eventbrite-react/rules/react-a11y.js
packages/eslint-config-eventbrite-react/rules/react.js
packages/eslint-config-eventbrite/rules/es6.js

After merging #62, I tested the ESLint rules in EDS to see if they all made sense. Some of them needed some tweaks or flat out removal.
After this, we should be able to release new major versions of each package.

Tweak ESLint configs

---

.travis.yml

Adding multiple deploy providers to the `.travis.yml`, one for each ESLint package.
When we push a new version of a package, we also push a new tag that is `[packageName]-v[versionNumber]`. We match on the package name to do the respective `yarn publish` for that package.
> NOTE: This will need `$NPM_TOKEN` set in Travis enviornment variables.

Add support for ESLint package Travis deployment

---

.travis.yml
package.json
yarn.lock

From all the examples of Yarn workspaces I've seen, the `package.json` is at the repo root instead of in the `packages/` folder as we currently have it.
This actually makes life easier because there's no need to `cd packages` anymore to `yarn`, `yarn test` & `yarn publish`.

Move workspace root to repo root

---

.travis.yml

I had `TRAVIS_TAG` instead of `$TRAVIS_TAG` for the environment variable regular expression match.
Also, while I'm at it, switching from `.*` to `.+`.

Fix Travis deploy condition

---

.travis.yml

For some reason `travis-deploy-once` needs `GITHUB_TOKEN` set in the environment (or passed in) in order to work, which makes no sense because we won't be writing anything to Github. It's probably because it's typically used with `semantic-release` which _does_ write to Github.
So instead, going to use the `node` conditional deployment filter and have it only deploy for the `"node"` job (i.e. latest version of node).

Remove travis-deploy-once in favor of node filter

---

.travis.yml

`yarn publish` for some reason asks for the new version of the package, makes it pretty much useless in a CI environment. I want it to just publish the files at the version _already_ in the `package.json`. This is what `npm publish` does so switching to that in hopes that it works as intended.

Switch to npm publish instead of yarn publish

---

.npmrc
.travis.yml

[`Build #88`](https://travis-ci.org/eventbrite/javascript/jobs/383401916) failed because of an authorization error.
In Travis we have `NPM_TOKEN` as an environment variable, but it's not automagically read. We need to update the registry URL to include it per: https://docs.npmjs.com/private-modules/ci-server-config#setting-up-a-project-specific-npmrc-file.
Then `npm publish` should have the authorization it needs.
Tried committing a `.npmrc` file (see [`Build #89`](https://travis-ci.org/eventbrite/javascript/builds/383421546)), but that broke PRs because `NPM_TOKEN` isn't available in builds from PRs the outside. So instead in `before_deploy` we'll create the `.npmrc` file on the fly. This is was `semantic-release` and other utilities do behind the scenes.

Add .npmrc file to set authToken

---

.travis.yml

Based on [`Build #92`](https://travis-ci.org/eventbrite/javascript/jobs/383442045), Travis cleans up the build artificats (`git stash --all`) **after** `before_deploy` is run and before `deploy` is executed. This means that the temporary `.npmrc` file that was written with PR #70 was removed before deploying. As a result no authentication again.
Passing `skip_cleanup: true` should do the trick. Not sure if it needs to be passed to each or if it could be shared at the top under `deploy`, but going the safe route and adding to each.

Add skip_cleanup to each deploy

---

packages/eslint-config-eventbrite-legacy/CHANGELOG.md
packages/eslint-config-eventbrite-react/CHANGELOG.md
packages/eslint-config-eventbrite-react/rules/react.js
packages/eslint-config-eventbrite/CHANGELOG.md

Lists out the new rules added, those made stronger, and those relaxed across `eslint-config-eventbrite-legacy`, `eslint-config-eventbrite` & `eslint-config-eventbrite-react`.
Also noticed one incorrect URL in the rules definition.
Also realized that we had forgotten to include v5 of `eslint-config-eventbrite-react` in the CHANGELOG.

 Add updated CHANGELOG for 3 eslint packages

---

general/README.md

Inside general guidlines for JavaScript, peoplesFavoriteFruits ES6 and ES5 functional examples for iterating over a list were returning letters in the property names instead of the favorite fruit values.

Fixed some errors with the iterator example behavior

---

packages/eslint-config-eventbrite-legacy/rules/style.js
packages/eslint-config-eventbrite/rules/best-practices.js

Adds rule to enforce spacing before and after keywords which is a common best readability practice in JavaScript. Makes sure that this:
```
if(foo){
// ...
}else{
// ...
}
```
Is written as:
```
if (foo) {
// ...
} else {
// ...
}
```
Hattip to @melissaroman-eb for finding this style inconsistency in a recent diff I posted.
Fixes #79

Add keyword spacing lint rule

---

packages/eslint-config-eventbrite/rules/es6.js

This rule is nice to remind developers the fact that we can return a single operation from an arrow function without needing the 'return' clause. However, it is also problematic due to several things:
First, this rule doesn't take into account that maybe that single return value is composed of a chain of operations, so it won't be as readable if returned all at once.
Second, when debugging a react application, sometimes we want to add a 'debugger' clause in the code before the return. When this happens, we are forced to first, add curly braces and a return statement, then add the debugger, and once we end debugging, undo the previous operations to not break this rule. This can be annoying and a waste of time.
In this PR, I suggest to get rid of the rule altogether, but I would be also …

Removes arrow-body-style rule in ES6 eslint rules

---

packages/eslint-config-eventbrite-react/rules/react.js

We have established at EB a way that we write react code, and many components utilize functional helper components to abstract portions of a larger, more complex, component. 
As we continue with this pattern we miss out on the potential performance boosts PureComponents provide as stateless functional components default to standard behavior.
React 16.6 introduced the `memo` api for stateless components: https://reactjs.org/blog/2018/10/23/react-v-16-6.html but until we get to that point (and decide if that is the pattern we want to use) I believe we are losing potential performance increases provided by react. So I vote to remove it so we can enable ourselves to be more performant :) 
ps. If instances of "component dumping grounds" (one of the original impetuses for this rule) begin to …

Remove rule forbidding multiple class style component declarations
